services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    region: us
    autoDeploy: true

databases:
  - name: postgres-db
    plan: free
    databaseName: flaskdb
